version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pathpilot_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1

  path-pilot-service:
    image: floredenis2001/path-pilot-service:17.06.2024.18.50.39
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_started
  clientapp:
    image: floredenis2001/path-pilot-client:latest
    networks:
      - mynetwork
    ports:
      - "5000:80"
    depends_on:
      - webapp
  nginx:
    image: floredenis2001/path-pilot-proxy:latest
    networks:
      - mynetwork
    ports:
      - "8080:80"
    depends_on:
      - clientapp
      - webapp