version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pathpilot_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1
  path-pilot-service:
    image: floredenis2001/path-pilot-server:01.07.2024.13.05.10
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  clientapp:
    image: floredenis2001/path-pilot-client:21.06.2024.14.45.02
    networks:
      - mynet
    ports:
      - "80:80"
    depends_on:
      - path-pilot-service
    environment:
      - REACT_APP_ENV=prod
  nginx:
    image: floredenis2001/path-pilot-proxy:v2
    networks:
      - mynet
    ports:
      - "8080:80"
    depends_on:
      - clientapp
      - path-pilot-service